questions:
  #
  # BASE
  # 
  - &cluster_name
    identifier: cluster_name
    question: 'Name of the cluster'

  - &root_password
    identifier: root_password
    question: 'Password to use for root user (generate with `openssl passwd -1`)'

  - &publickey
    identifier: publickey
    question: 'Public SSH key for the root user'

  #
  # GROUPS
  #
  - &hostname_range
    identifier: hostname_range
    question: 'List of hosts for the group (in genders format, e.g. "node01,node[05-08]")'
    
  - &secondary_groups
    identifier: secondary_groups
    question: 'Additional genders groups for this node/group to appear in (e.g. "compute,rack1")'
    default: '<%= config.cluster %>'

  - &role
    identifier: role
    question: "Role of nodes in this group"
    choices:
      - 'service'
      - 'login'
      - 'compute'
      - 'storage'
      - 'other'
    default: 'other'

  #
  # NETWORKS
  # 
  - &domain
    identifier: domain
    question: 'Fully-qualified domain name for cluster nodes'
    default: '<%= domain.config.cluster %>.cluster.local'

  - &network2_defined
    identifier: network2_defined
    question: 'Define a second network?'
    type: boolean

  - &network3_defined
    identifier: network3_defined
    question: 'Define a third network?'
    type: boolean


domain:
  # BASE
  - *cluster_name
  - *root_password
  - *publickey

  # NETWORKS
  - *domain
  - *network2_defined
  - *network3_defined

group: 
  # BASE
  - *hostname_range
  - *role
  - *secondary_groups

  # NETWORKS
  - *network2_defined
  - *network3_defined
  
node:
  # BASE
  - *hostname_range

local: []
