<%
require 'ipaddr'
def to_cidr(network,netmask)
  "#{network.to_s}/#{IPAddr.new(netmask.to_s).to_i.to_s(2).count('1')}"
end

-%>
---
Description: 'Flight Domain Template'
Mappings:
  RegionMap:
    eu-west-1:
      "AMI": "ami-d266dfab"
    eu-west-2:
      "AMI": "ami-c5f11ea2"
Resources:
<% name=node.name -%>
<% node.config.networks.each do |netname,network| -%>
<% if network.defined -%>

  <%=name%><%=netname%>Interface:
    Type: AWS::EC2::NetworkInterface
    Properties:
      SourceDestCheck: false
      GroupSet:
        - !Ref <%=node.config.cluster%>SecurityGroup
      PrivateIpAddress: <%=network.ip %>
      SubnetId: !Ref <%=node.config.cluster%><%=netname%>Subnet
      Tags:
        -
          Key: 'Name'
          Value: '<%=name%>'
        -
          Key: 'alcescluster'
          Value: <%=node.config.cluster%>
<% end -%>
<% end -%>

  <%=node.name%>:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: !Select
        - 0
        - Fn::GetAZs: !Ref 'AWS::Region'
      ImageId: !FindInMap ["RegionMap", !Ref "AWS::Region", "AMI"]
      InstanceType: t2.small
      Monitoring: true
      KeyName: aws_ireland
      NetworkInterfaces:
<% count=0; node.config.networks.each do |name,network| -%>
<% if network.defined -%>
        -
          NetworkInterfaceId: !Ref <%=node.name%><%=name%>Interface
          DeviceIndex: <%=count%>
<% count+=1 -%>
<% end -%>
<% end -%>

      Tags:
        -
          Key: 'Name'
          Value: '<%=name%>'
        -
          Key: 'alcescluster'
          Value: <%=node.config.cluster%>
      UserData:
        Fn::Base64:
          Fn::Join:
            - ''
            - - "#cloud-config\n"
              - "hostname: <%=name%>\n"
              - "fqdn: <%=node.config.networks.pri.hostname%>\n"
              - "runcmd:\n"
              - "  - curl <%= node.config.nodescripturl %> | /bin/bash | tee /tmp/mainscript-default-output\n"

<% if node.config.role == 'login' -%>
  <%=node.name%>publicIp:
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc

  <%=node.name%>publicIpAssociation:
    Type: AWS::EC2::EIPAssociation
    Properties:
      NetworkInterfaceId: !Ref <%=node.name%>priInterface
      AllocationId: !GetAtt <%=node.name%>publicIp.AllocationId
<% end -%>

Outputs:
  domaincloudID:
    Description: domaincloudID
    Value: !Ref <%=config.cluster%>Network
<% config.networks.each do |networkname,network|-%>
<% if network.defined -%>
  <%=networkname%>cloudID:
    Description: <%=networkname%>cloudID
    Value: !Ref <%=config.cluster%><%=networkname%>Subnet
<% end -%>
<% end -%>
  <%=node.name%>ID:
    Description: <%=node.name%>ID
    Value: !Ref <%=node.name%>
